services:
  api:
    image: nodejs
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    restart: unless-stopped
    environment:
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=example
      - MONGO_HOSTNAME=database
      - MONGO_PORT=27017
      - MONGO_DB=app
    ports:
      - "8080:8080"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      - app-network
    command: /home/node/app/node_modules/.bin/nodemon index.js
    depends_on:
      - database
  database:
    image: mongo
    container_name: database
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:  
      - dbdata:/data/db   
    networks:
      - app-network  
        #  mongo-express:
        #    image: mongo-express
        #    restart: always
        #    ports:
        #      - 8081:8081
        #    environment:
        #      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
        #      - ME_CONFIG_MONGODB_ADMINPASSWORD=example
        #      - ME_CONFIG_MONGODB_URL=mongodb://root:example@database:27017/
        #    networks:
        #      - app-network
        #    depends_on:
        #      - database

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  node_modules:  
